import type { DeepResearchGuide, GuideLocale, ProviderId, SourceRecord } from './model';

export const GUIDE_VERSION = '1.0.0';
export const GUIDE_RESEARCH_CUTOFF = '2026-07-17';

const sources: SourceRecord[] = [
  {
    id: 'GOOGLE-2024-12-11-DEEP-RESEARCH',
    provider: 'Google',
    title: 'Try Deep Research and our new experimental model in Gemini, your AI assistant',
    url: 'https://blog.google/products-and-platforms/products/gemini/google-gemini-deep-research/',
    publicationDate: '2024-12-11',
    accessedDate: GUIDE_RESEARCH_CUTOFF,
    authority: 'official-product-announcement',
    claimScope: [
      'Deep Research product name and Gemini Advanced launch',
      'Gemini 1.5 Pro launch model selection',
      'editable multi-step research plan',
      'iterative web research and comprehensive reports',
      'links to original sources and Google Docs export',
      'agentic system and one-million-token context claim',
    ],
  },
  {
    id: 'GOOGLE-2025-03-13-DEEP-RESEARCH-2-FLASH',
    provider: 'Google',
    title: 'New Gemini app features, available to try at no cost',
    url: 'https://blog.google/products-and-platforms/products/gemini/new-gemini-app-features-march-2025/',
    publicationDate: '2025-03-13',
    accessedDate: GUIDE_RESEARCH_CUTOFF,
    authority: 'official-product-announcement',
    claimScope: [
      'Deep Research upgrade to Gemini 2.0 Flash Thinking Experimental',
      'planning searching reasoning analysis and reporting stages',
      'broader global trial availability and 45-plus languages',
      'progress presentation while browsing',
    ],
  },
  {
    id: 'GOOGLE-2025-03-19-AUDIO-OVERVIEWS',
    provider: 'Google',
    title: '6 tips to get the most out of Gemini Deep Research',
    url: 'https://blog.google/products-and-platforms/products/gemini/tips-how-to-use-deep-research/',
    publicationDate: '2025-03-19',
    accessedDate: GUIDE_RESEARCH_CUTOFF,
    authority: 'official-product-guidance',
    claimScope: [
      'Audio Overviews for Deep Research reports',
      'Google Docs export and works cited behavior',
      'official product usage framing',
    ],
  },
  {
    id: 'GOOGLE-2025-05-20-PRIVATE-SOURCES',
    provider: 'Google',
    title: 'Gemini gets more personal, proactive and powerful',
    url: 'https://blog.google/products-and-platforms/products/gemini/gemini-app-updates-io-2025/',
    publicationDate: '2025-05-20',
    accessedDate: GUIDE_RESEARCH_CUTOFF,
    authority: 'official-product-announcement',
    claimScope: [
      'private PDF and image sources in Deep Research',
      'planned Google Drive and Gmail research integration',
    ],
  },
  {
    id: 'GOOGLE-2025-DEEP-RESEARCH-2-5-PRO',
    provider: 'Google',
    title: 'Deep Research is now available on Gemini 2.5 Pro Experimental',
    url: 'https://blog.google/products-and-platforms/products/gemini/deep-research-gemini-2-5-pro-experimental/',
    publicationDate: null,
    accessedDate: GUIDE_RESEARCH_CUTOFF,
    authority: 'official-product-announcement',
    claimScope: [
      'Deep Research availability on Gemini 2.5 Pro Experimental',
      'web Android and iOS access',
      'Google Workspace availability note',
    ],
    editorialNote:
      'The current page did not expose a reliable publication date in the retrieved official record. Do not invent a date.',
  },
  {
    id: 'OPENAI-2025-02-02-DEEP-RESEARCH',
    provider: 'OpenAI',
    title: 'Introducing deep research',
    url: 'https://openai.com/index/introducing-deep-research/',
    publicationDate: '2025-02-02',
    accessedDate: GUIDE_RESEARCH_CUTOFF,
    authority: 'official-product-announcement',
    claimScope: [
      'deep research product name and ChatGPT launch',
      'agentic multi-step internet research',
      'launch model described as an early version of OpenAI o3',
      'browser and Python tool use',
      'text image PDF and uploaded-file analysis',
      'five-to-thirty-minute task duration',
      'citations and progress/source sidebar',
      'launch limitations and later dated updates',
    ],
  },
  {
    id: 'XAI-2025-02-19-GROK-3-DEEPSEARCH',
    provider: 'xAI',
    title: 'Grok 3 Beta — The Age of Reasoning Agents',
    url: 'https://x.ai/news/grok-3',
    publicationDate: '2025-02-19',
    accessedDate: GUIDE_RESEARCH_CUTOFF,
    authority: 'official-product-announcement',
    claimScope: [
      'DeepSearch product name',
      'Grok 3 launch context',
      'xAI description of DeepSearch as its first agent',
      'internet access and code interpreters',
      'dynamic query refinement',
      'conflicting-fact and opinion synthesis',
      'summary trace and report framing',
    ],
  },
  {
    id: 'ANTHROPIC-2025-04-15-RESEARCH',
    provider: 'Anthropic',
    title: 'Claude takes research to new places',
    url: 'https://claude.com/blog/research',
    publicationDate: '2025-04-15',
    accessedDate: GUIDE_RESEARCH_CUTOFF,
    authority: 'official-product-announcement',
    claimScope: [
      'Research product name',
      'web and Google Workspace research',
      'multiple searches that build on each other',
      'automatic exploration of question angles',
      'citations and comprehensive answers in minutes',
      'early beta launch plans and regions',
      'secure retrieval-augmented generation for enterprise document cataloging',
    ],
  },
  {
    id: 'ANTHROPIC-CURRENT-RESEARCH-HELP',
    provider: 'Anthropic',
    title: 'Using Research on Claude',
    url: 'https://support.anthropic.com/en/articles/11088861-using-research-on-claude-ai',
    publicationDate: null,
    accessedDate: GUIDE_RESEARCH_CUTOFF,
    authority: 'official-help-documentation',
    claimScope: [
      'current beta labeling',
      'paid-plan availability',
      'web desktop and mobile availability',
      'web-search prerequisite',
      'internal-context and web behavior',
    ],
  },
  {
    id: 'DEEPSEEK-2024-12-10-WEB-SEARCH',
    provider: 'DeepSeek',
    title: 'DeepSeek V2 系列收官，联网搜索上线官网',
    url: 'https://api-docs.deepseek.com/zh-cn/news/news1210',
    publicationDate: '2024-12-10',
    accessedDate: GUIDE_RESEARCH_CUTOFF,
    authority: 'official-product-announcement',
    claimScope: [
      '联网搜索 product-mode name',
      'DeepSeek-V2.5-1210 launch context',
      'parallel keyword extraction and search',
      'deep reading of many webpages',
      'web-only availability and no API search at launch',
    ],
  },
  {
    id: 'DEEPSEEK-2025-01-15-APP',
    provider: 'DeepSeek',
    title: 'Introducing DeepSeek App',
    url: 'https://api-docs.deepseek.com/news/news250115',
    publicationDate: '2025-01-15',
    accessedDate: GUIDE_RESEARCH_CUTOFF,
    authority: 'official-product-announcement',
    claimScope: [
      'Web search and Deep-Think mode as separate app features',
      'DeepSeek-V3 app launch context',
      'file upload and text extraction',
    ],
  },
  {
    id: 'DEEPSEEK-2025-01-20-R1',
    provider: 'DeepSeek',
    title: 'DeepSeek-R1 发布，性能对标 OpenAI o1 正式版',
    url: 'https://api-docs.deepseek.com/zh-cn/news/news250120/',
    publicationDate: '2025-01-20',
    accessedDate: GUIDE_RESEARCH_CUTOFF,
    authority: 'official-model-announcement',
    claimScope: [
      'DeepSeek-R1 release',
      'deepseek-reasoner API name',
      'DeepThink website and app mode',
      'large-scale reinforcement learning in post-training',
      'open weights and MIT license claims',
    ],
  },
  {
    id: 'DEEPSEEK-2025-05-28-R1-0528',
    provider: 'DeepSeek',
    title: 'DeepSeek-R1 更新，思考更深，推理更强',
    url: 'https://api-docs.deepseek.com/zh-cn/news/news250528',
    publicationDate: '2025-05-28',
    accessedDate: GUIDE_RESEARCH_CUTOFF,
    authority: 'official-model-announcement',
    claimScope: [
      'DeepSeek-R1-0528 model update',
      'DeepThink mode association',
      'increased post-training compute and reasoning-depth claims',
    ],
  },
  {
    id: 'DEEPSEEK-2025-08-21-V3-1',
    provider: 'DeepSeek',
    title: 'DeepSeek-V3.1 发布',
    url: 'https://api-docs.deepseek.com/zh-cn/news/news250821',
    publicationDate: '2025-08-21',
    accessedDate: GUIDE_RESEARCH_CUTOFF,
    authority: 'official-model-announcement',
    claimScope: [
      'hybrid Think and Non-Think architecture',
      'DeepThink toggle',
      'agent and tool-use improvements',
      'complex multi-step search-task claims',
    ],
  },
  {
    id: 'DEEPSEEK-CURRENT-CHANGELOG',
    provider: 'DeepSeek',
    title: 'Change Log',
    url: 'https://api-docs.deepseek.com/updates/',
    publicationDate: null,
    accessedDate: GUIDE_RESEARCH_CUTOFF,
    authority: 'official-change-log',
    claimScope: [
      'dated model and API transitions',
      'current separation of chat and reasoning modes',
      'historical verification of DeepSeek-R1 and V3-series updates',
    ],
  },
];

const zhTW: DeepResearchGuide = {
  schemaVersion: 1,
  guideVersion: GUIDE_VERSION,
  locale: 'zh-TW',
  researchCutoff: GUIDE_RESEARCH_CUTOFF,
  title: 'Deep Research 是什麼？',
  subtitle: '名稱、歷史、技術概念、供應商差異與這個 archive 保存的內容',
  disclaimer:
    '這是一份中立的產品類別說明，不是供應商排名、採購建議或正確性保證。可變動事實以官方來源為準，宣傳性敘述保留供應商歸屬。',
  ui: {
    open: '說明',
    close: '關閉說明',
    source: '官方來源',
    openOfficialSource: '在外部瀏覽器開啟官方來源',
    researchCutoff: '研究截止日',
    providerClaim: '供應商宣稱',
    verifiedFact: '官方可核對事實',
    repositorySynthesis: '本 repo 的中立整理',
    sourceCount: '{count} 筆官方來源',
    firstLaunchTitle: '這個 archive 保存什麼？',
    firstLaunchBody:
      'Research Observatory 保存長篇 LLM 研究成果，包括 Deep Research、DeepSearch、Research 與相近搜尋／推理工作流產出的報告。',
    firstLaunchOpen: '了解 Deep Research',
    firstLaunchDismiss: '稍後再看',
    aboutArchive: '關於 Deep Research 類報告',
    field: '欄位',
    launch: '推出日期',
    modelContext: '模型背景',
    characteristics: '主要特色',
    limitations: '限制與注意事項',
    published: '發布日期',
    accessed: '查核日期',
    authority: '來源類型',
    claimScope: '支持的敘述範圍',
    editorialMethod: '編輯方法',
    notStated: '未可靠揭露',
    whyPreserve: '為什麼要保存報告？',
    whatPreserved: '保存哪些內容',
    notGuaranteed: '不保證哪些事項',
  },
  sections: [
    {
      id: 'guide.overview',
      label: '快速理解',
      title: '一句話理解 Deep Research',
      intro: '先理解產品類別，再看各家命名。',
    },
    {
      id: 'guide.workflow',
      label: '它怎麼運作',
      title: '典型研究代理流程',
      intro: '實際內部實作不公開，但產品層工作流通常包含下列階段。',
    },
    {
      id: 'guide.distinctions',
      label: '搜尋、思考與研究',
      title: '不要把搜尋、推理與研究代理混為一談',
      intro: '三者可以組合，但不是同義詞。',
    },
    {
      id: 'guide.timeline',
      label: '歷史時間線',
      title: '2024–2026 產品演進',
      intro: '日期、產品名稱與模型背景只在官方來源支持時記錄。',
    },
    {
      id: 'guide.providers',
      label: '各家怎麼稱呼',
      title: '五家供應商逐項解讀',
      intro: '同一問題空間，不同產品名稱與揭露程度。',
    },
    {
      id: 'guide.comparison',
      label: '中立比較',
      title: '可比較欄位與明確未知',
      intro: '比較產品形態，不產生總分或排名。',
    },
    {
      id: 'guide.archive',
      label: '這個 repo 保存什麼',
      title: '保存、組織、呈現與協助查核',
      intro: '保存報告不等於替內容或供應商背書。',
    },
    {
      id: 'guide.verify',
      label: '如何查核',
      title: '閱讀研究報告的十項檢查',
      intro: '大量引用和流暢排版仍需要抽查。',
    },
    {
      id: 'guide.sources',
      label: '來源與方法',
      title: '官方來源、截止日與編輯規則',
      intro: '所有來源隨應用離線打包，官方連結只透過安全外部開啟。',
    },
  ],
  overview: {
    definition:
      'Deep Research 類功能讓語言模型不只回答一次，而是先規劃研究工作、反覆搜尋或讀取多個來源、根據中途發現修正方向，最後產出具來源連結或引用的長篇整理。',
    umbrellaNote:
      'Deep Research 不是正式標準或跨公司協定。本 repo 把它當成方便理解的上位詞，不代表所有產品完全等價，也不代表所有收錄文章都由同名功能生成。',
    namingRows: [
      {
        providerId: 'google',
        provider: 'Google Gemini',
        productName: 'Deep Research',
        exactBrand: '使用相同品牌',
      },
      {
        providerId: 'openai',
        provider: 'OpenAI ChatGPT',
        productName: 'deep research',
        exactBrand: '使用相同品牌，官方常用小寫',
      },
      {
        providerId: 'xai',
        provider: 'xAI Grok',
        productName: 'DeepSearch',
        exactBrand: '相近研究代理，名稱不同',
      },
      {
        providerId: 'anthropic',
        provider: 'Anthropic Claude',
        productName: 'Research',
        exactBrand: '官方名稱較短',
      },
      {
        providerId: 'deepseek',
        provider: 'DeepSeek',
        productName: '聯網搜尋 / Web Search；DeepThink / 深度思考',
        exactBrand: '未找到獨立 Deep Research 品牌證據',
      },
    ],
  },
  workflow: [
    { title: '界定問題', detail: '確認範圍、時間、地區、格式與使用者提供的檔案。' },
    { title: '建立計畫', detail: '拆成子問題、候選來源與需要驗證的項目。' },
    { title: '多來源檢索', detail: '搜尋網頁、文件、PDF、圖片或已連接的內部資料。' },
    { title: '反覆修正', detail: '根據新資訊增加關鍵字、回溯、改查方向或處理衝突。' },
    { title: '分析與整合', detail: '比較來源、找出共同點、差異、缺口與不確定性。' },
    { title: '產出報告', detail: '形成具結構的長篇結果，通常附引用、連結或 works cited。' },
    { title: '後續加工', detail: '部分產品支援匯出、視覺化、Audio Overview 或企業資料連接。' },
  ],
  distinctions: [
    {
      title: '一般網頁搜尋',
      detail: '快速找出頁面、摘要或答案，使用者通常仍需自行比較來源與組織報告。',
    },
    {
      title: '有搜尋工具的普通聊天',
      detail: '可能只搜尋一次或少量幾次後直接回答，不一定建立或反覆修正研究計畫。',
    },
    {
      title: 'Thinking / DeepThink',
      detail: '代表更多推理或測試時計算；可能不連網。思考得更久不等於已完成外部研究。',
    },
    {
      title: 'Deep Research 類代理',
      detail: '把規劃、反覆檢索、分析、整合與引用報告組成較長工作軌跡。',
    },
  ],
  timeline: [
    {
      id: 'deepseek-web-search',
      date: '2024-12-10',
      providerId: 'deepseek',
      title: 'DeepSeek 網頁端上線「聯網搜尋」',
      modelContext: 'DeepSeek-V2.5-1210',
      summary:
        '官方描述複雜問題會抽取多個關鍵字並行搜尋、深入閱讀大量網頁，但未命名為 Deep Research。',
      sourceIds: ['DEEPSEEK-2024-12-10-WEB-SEARCH'],
      attribution: 'verified-fact',
    },
    {
      id: 'gemini-launch',
      date: '2024-12-11',
      providerId: 'google',
      title: 'Gemini 推出 Deep Research',
      modelContext: 'Gemini 1.5 Pro with Deep Research',
      summary:
        '向 Gemini Advanced 推出可修改／批准研究計畫、反覆搜尋、產生含原始來源連結報告與 Docs 匯出的功能。',
      sourceIds: ['GOOGLE-2024-12-11-DEEP-RESEARCH'],
      attribution: 'verified-fact',
    },
    {
      id: 'deepseek-app',
      date: '2025-01-15',
      providerId: 'deepseek',
      title: 'DeepSeek App 分列 Web Search 與 Deep-Think',
      modelContext: 'DeepSeek-V3',
      summary: '官方功能清單把搜尋與推理模式分開，顯示兩者不是同一個命名產品。',
      sourceIds: ['DEEPSEEK-2025-01-15-APP'],
      attribution: 'verified-fact',
    },
    {
      id: 'deepseek-r1',
      date: '2025-01-20',
      providerId: 'deepseek',
      title: 'DeepSeek-R1 與 DeepThink',
      modelContext: 'DeepSeek-R1 / deepseek-reasoner',
      summary: '推理模型與強化學習里程碑，不應倒寫成獨立 Deep Research 發布。',
      sourceIds: ['DEEPSEEK-2025-01-20-R1'],
      attribution: 'verified-fact',
    },
    {
      id: 'openai-launch',
      date: '2025-02-02',
      providerId: 'openai',
      title: 'ChatGPT 推出 deep research',
      modelContext: 'OpenAI o3 早期版本',
      summary:
        '可執行多步驟網路研究、使用瀏覽器與 Python、處理文字圖片 PDF 和上傳檔案，通常耗時 5–30 分鐘並產出具引用報告。',
      sourceIds: ['OPENAI-2025-02-02-DEEP-RESEARCH'],
      attribution: 'verified-fact',
    },
    {
      id: 'xai-launch',
      date: '2025-02-19',
      providerId: 'xai',
      title: 'Grok 3 推出 DeepSearch',
      modelContext: 'Grok 3',
      summary:
        'xAI 稱其為第一個 agent；會查詢缺失背景、動態調整方法、整合衝突事實與意見並提供報告。',
      sourceIds: ['XAI-2025-02-19-GROK-3-DEEPSEARCH'],
      attribution: 'vendor-claim',
    },
    {
      id: 'gemini-flash-thinking',
      date: '2025-03-13',
      providerId: 'google',
      title: 'Gemini Deep Research 升級',
      modelContext: 'Gemini 2.0 Flash Thinking Experimental',
      summary: '官方把規劃、搜尋、推理、分析與報告列為整體流程，並擴大免費試用與語言範圍。',
      sourceIds: ['GOOGLE-2025-03-13-DEEP-RESEARCH-2-FLASH'],
      attribution: 'verified-fact',
    },
    {
      id: 'gemini-audio',
      date: '2025-03-19',
      providerId: 'google',
      title: '加入 Audio Overviews',
      modelContext: 'Gemini Deep Research',
      summary: '研究報告可轉為 podcast 風格 Audio Overview，並維持 Docs 匯出與 works cited。',
      sourceIds: ['GOOGLE-2025-03-19-AUDIO-OVERVIEWS'],
      attribution: 'verified-fact',
    },
    {
      id: 'anthropic-launch',
      date: '2025-04-15',
      providerId: 'anthropic',
      title: 'Claude 推出 Research',
      modelContext: '公告未指定專用模型；時期背景為 Claude 3.7 Sonnet 產品線',
      summary: '在網頁與內部工作資料進行多次彼此承接的搜尋，數分鐘內產出含可檢查引用的綜合回答。',
      sourceIds: ['ANTHROPIC-2025-04-15-RESEARCH'],
      attribution: 'verified-fact',
    },
    {
      id: 'openai-lightweight',
      date: '2025-04-24',
      providerId: 'openai',
      title: 'OpenAI 加入輕量版 deep research',
      modelContext: 'o4-mini 版本',
      summary: '完整版額度用完後切換至成本較低版本，證明產品模式可由不同模型路由。',
      sourceIds: ['OPENAI-2025-02-02-DEEP-RESEARCH'],
      attribution: 'verified-fact',
    },
    {
      id: 'gemini-private-sources',
      date: '2025-05-20',
      providerId: 'google',
      title: 'Gemini 混合公開與私人來源',
      modelContext: 'Gemini Deep Research',
      summary: '支援使用者 PDF 與圖片，並預告 Drive 和 Gmail 研究整合。',
      sourceIds: ['GOOGLE-2025-05-20-PRIVATE-SOURCES'],
      attribution: 'verified-fact',
    },
    {
      id: 'deepseek-r1-0528',
      date: '2025-05-28',
      providerId: 'deepseek',
      title: 'R1-0528 強化 DeepThink',
      modelContext: 'DeepSeek-R1-0528',
      summary: '官方稱增加後訓練算力與思考深度；仍是推理路線而非同名研究產品。',
      sourceIds: ['DEEPSEEK-2025-05-28-R1-0528'],
      attribution: 'vendor-claim',
    },
    {
      id: 'openai-agent-browser',
      date: '2025-07-17',
      providerId: 'openai',
      title: 'deep research 整合視覺化瀏覽器',
      modelContext: 'ChatGPT agent',
      summary: '更新說明指出可透過 agent 視覺瀏覽器進行更廣、更深研究，原功能仍留在工具選單。',
      sourceIds: ['OPENAI-2025-02-02-DEEP-RESEARCH'],
      attribution: 'verified-fact',
    },
    {
      id: 'deepseek-v31',
      date: '2025-08-21',
      providerId: 'deepseek',
      title: 'DeepSeek-V3.1 強化 agent 與複雜搜尋',
      modelContext: 'DeepSeek-V3.1 hybrid Think / Non-Think',
      summary:
        '工具使用、代理任務與多步驟複雜搜尋能力提升，但官方仍未建立獨立 Deep Research 品牌。',
      sourceIds: ['DEEPSEEK-2025-08-21-V3-1'],
      attribution: 'verified-fact',
    },
    {
      id: 'openai-mcp',
      date: '2026-02-10',
      providerId: 'openai',
      title: 'deep research 加入 MCP、可信網站與中途修正',
      modelContext: 'ChatGPT deep research',
      summary: '可連接 MCP 或 app、限制可信網站、追蹤進度並在執行途中以新提示或來源修正研究。',
      sourceIds: ['OPENAI-2025-02-02-DEEP-RESEARCH'],
      attribution: 'verified-fact',
    },
  ],
  providers: [
    {
      id: 'google',
      provider: 'Google Gemini',
      productName: 'Deep Research',
      namingNote: '本範圍最早直接使用 Deep Research 品牌的官方產品。',
      launchDate: '2024-12-11',
      modelContext:
        '首發為 Gemini 1.5 Pro with Deep Research；後續升級至 2.0 Flash Thinking Experimental 與 2.5 Pro Experimental。',
      summary:
        '以可修改／批准的研究計畫作為重要人類介入點，之後演進至進度呈現、Audio Overview、私人 PDF／圖片與更多輸出形式。',
      characteristics: [
        '可先審核研究計畫',
        '反覆搜尋與精煉',
        '原始來源連結與 Docs 匯出',
        'Audio Overview 與私人來源',
      ],
      limitations: [
        'Google Search 的 Deep Search 是另一產品，不應混寫',
        '模型與可用範圍會隨時間更換',
      ],
      sourceIds: [
        'GOOGLE-2024-12-11-DEEP-RESEARCH',
        'GOOGLE-2025-03-13-DEEP-RESEARCH-2-FLASH',
        'GOOGLE-2025-03-19-AUDIO-OVERVIEWS',
        'GOOGLE-2025-05-20-PRIVATE-SOURCES',
      ],
    },
    {
      id: 'openai',
      provider: 'OpenAI ChatGPT',
      productName: 'deep research',
      namingNote: '官方英文通常以小寫產品寫法呈現。',
      launchDate: '2025-02-02',
      modelContext: '首發由 o3 早期版本驅動；後續增加 o4-mini 輕量版與 ChatGPT agent 視覺瀏覽器。',
      summary:
        '著重代理、工具與長時間任務，官方公開 browser、Python、end-to-end RL、多模態文件與可回溯多步驟 trajectory 等線索。',
      characteristics: [
        '瀏覽器與 Python 工具',
        '文字、圖片、PDF、試算表',
        '具引用報告與進度／來源摘要',
        'MCP、app、可信網站與中途修正',
      ],
      limitations: ['官方承認可能幻覺、誤判來源權威與信心校準不足', '功能名稱不等於單一固定模型'],
      sourceIds: ['OPENAI-2025-02-02-DEEP-RESEARCH'],
    },
    {
      id: 'xai',
      provider: 'xAI Grok',
      productName: 'DeepSearch',
      namingNote: '名稱不同，但官方把它定位為研究型 reasoning agent。',
      launchDate: '2025-02-19',
      modelContext: 'Grok 3，具網路存取與 code interpreter。',
      summary:
        '重點是找出缺失背景、動態調整策略、處理衝突事實與意見，最後提供精簡而完整的報告與 summary trace。',
      characteristics: [
        '動態查缺口與調整方法',
        '整合衝突資訊',
        '網路與 code interpreter',
        '報告與 summary trace',
      ],
      limitations: ['「seek the truth」屬品牌宣稱，不是獨立正確率保證', '公開技術與限制細節較少'],
      sourceIds: ['XAI-2025-02-19-GROK-3-DEEPSEARCH'],
    },
    {
      id: 'anthropic',
      provider: 'Anthropic Claude',
      productName: 'Research',
      namingNote: '官方名稱較短，Research 是產品功能而非模型名稱。',
      launchDate: '2025-04-15',
      modelContext: '推出公告未指定專用模型；Claude 3.7 Sonnet 僅是同時期產品線背景。',
      summary:
        '差異化敘事是把公開網路與 Gmail、Calendar、Docs、企業文件等工作資料連接，使用多次彼此承接的搜尋。',
      characteristics: [
        '公開網路與 Workspace 資料',
        '多次搜尋彼此承接',
        '可檢查引用',
        '企業文件 cataloging 與安全 RAG',
      ],
      limitations: ['初期與目前可用方案／地區會變動', '不可推論固定由某一模型執行'],
      sourceIds: ['ANTHROPIC-2025-04-15-RESEARCH', 'ANTHROPIC-CURRENT-RESEARCH-HELP'],
    },
    {
      id: 'deepseek',
      provider: 'DeepSeek',
      productName: '聯網搜尋 / Web Search；DeepThink / 深度思考',
      namingNote: '相近能力組合，不創造不存在的「DeepSeek Deep Research」。',
      launchDate: '2024-12-10',
      modelContext: 'V2.5-1210 聯網搜尋、V3 App、R1 reasoner、V3.1 hybrid Think / Non-Think。',
      summary:
        '官方歷史提供搜尋、推理與 agent/tool 能力三條相鄰路線；它們可形成類似深度研究的體驗，但沒有獨立同名產品證據。',
      characteristics: [
        '多關鍵字並行搜尋與多網頁閱讀',
        'DeepThink 推理模式',
        'R1 強化學習與 reasoner API',
        'V3.1 agent、工具與複雜搜尋',
      ],
      limitations: ['搜尋與推理必須分開描述', '截至截止日沒有官方獨立 Deep Research 品牌'],
      sourceIds: [
        'DEEPSEEK-2024-12-10-WEB-SEARCH',
        'DEEPSEEK-2025-01-15-APP',
        'DEEPSEEK-2025-01-20-R1',
        'DEEPSEEK-2025-08-21-V3-1',
      ],
    },
  ],
  comparison: [
    {
      label: '官方名稱',
      values: {
        google: 'Deep Research',
        openai: 'deep research',
        xai: 'DeepSearch',
        anthropic: 'Research',
        deepseek: '聯網搜尋／Web Search、DeepThink／深度思考',
      },
    },
    {
      label: '可核對首發日期',
      values: {
        google: '2024-12-11',
        openai: '2025-02-02',
        xai: '2025-02-19',
        anthropic: '2025-04-15',
        deepseek: '聯網搜尋 2024-12-10；DeepThink App 2025-01-15；R1 2025-01-20',
      },
    },
    {
      label: '首發模型背景',
      values: {
        google: 'Gemini 1.5 Pro with Deep Research',
        openai: 'OpenAI o3 早期版本',
        xai: 'Grok 3',
        anthropic: '公告未指定專用模型',
        deepseek: 'V2.5-1210 搜尋；V3 App；R1 推理',
      },
    },
    {
      label: '計畫與迭代',
      values: {
        google: '可修改／批准多步驟計畫',
        openai: '規劃多步驟 trajectory、必要時回溯',
        xai: '查缺口並動態調整方法',
        anthropic: '多次搜尋彼此承接',
        deepseek: '抽取多個搜尋關鍵字；推理模式另行控制',
      },
    },
    {
      label: '來源範圍',
      values: {
        google: '公開網路、私人 PDF／圖片，後續 Drive/Gmail',
        openai: '公開網路、上傳檔案、app/MCP、可信網站',
        xai: '網路與 code interpreter',
        anthropic: '網路、Workspace、企業文件 catalog',
        deepseek: '網頁搜尋、上傳檔案、模型工具能力',
      },
    },
    {
      label: '典型輸出',
      values: {
        google: '多頁報告、來源、Docs、Audio Overview',
        openai: '具引用報告、進度／來源、視覺瀏覽器',
        xai: '完整精簡報告與 summary trace',
        anthropic: '綜合回答與可檢查引用',
        deepseek: '綜合搜尋回答或推理回答；無統一獨立研究產品定義',
      },
    },
    {
      label: '公開技術線索',
      values: {
        google: 'agentic system、長 context、Thinking model',
        openai: 'end-to-end RL、browser、Python、多模態',
        xai: 'reasoning、internet、code interpreter',
        anthropic: 'iterative search、Workspace、secure RAG',
        deepseek: 'parallel search、reasoner、RL、hybrid thinking、agent/tool use',
      },
    },
  ],
  archive: {
    rationale: [
      '網頁會修改、下架或改 URL。',
      '背後模型、工具、配額、地區與介面會更換。',
      '同一功能名稱可能改由不同模型驅動。',
      '提示、附件與當時限制會影響輸出。',
    ],
    preserves: [
      '使用者決定收錄的研究報告。',
      '報告結構與可用來源連結。',
      '本地圖片、圖表、程式碼與 Mermaid。',
      '日期、標籤、路徑、字數與搜尋索引。',
      '匯入與發布流程可保留的 provenance。',
    ],
    doesNotGuarantee: [
      '引用一定支持相鄰句子。',
      '所有來源都具權威性。',
      '報告沒有遺漏、偏誤或幻覺。',
      '產品進度畫面等於完整原始 chain-of-thought。',
      '相同 prompt 未來得到相同結果。',
      '不同供應商可直接公平排名。',
      '保存報告等於永久取得原來源權利。',
    ],
  },
  verificationChecklist: [
    '先看報告日期與當時模型／產品模式。',
    '確認問題範圍、地區、年份與條件。',
    '抽查關鍵引用是否存在且支持該句。',
    '區分官方文件、論文、新聞與論壇。',
    '尋找反例、衝突資料與缺席觀點。',
    '檢查幣別、期間、樣本、單位與統計口徑。',
    '辨認供應商 benchmark 與品質宣稱。',
    '不要把流暢度、長度或大量引用當正確性。',
    '醫療、法律、金融、安全與學術用途回到權威原始來源。',
    '保留版本背景，方便理解未來結果差異。',
  ],
  sources,
  editorialRules: [
    '頁首固定顯示研究截止日。',
    '可變動產品事實必須對應 source ID。',
    '未公開技術細節維持未知，不以確定語氣補完。',
    '不製作供應商總分或排名。',
    '供應商宣稱必須保留歸屬。',
    '改名、合併或停用時保留歷史名稱與日期。',
    '兩個 renderer 必須消費相同資料與 digest。',
  ],
  negativeFinding: {
    provider: 'DeepSeek',
    finding:
      '截至研究截止日，來源登錄沒有官方資料把搜尋與 DeepThink 合併命名為獨立 Deep Research 產品。',
    handlingRule: '呈現為相近能力組合，更新 Guide 時重新查核；不得自行創造產品名稱。',
  },
};

const en: DeepResearchGuide = {
  ...zhTW,
  locale: 'en',
  title: 'What is Deep Research?',
  subtitle:
    'Names, history, technical concepts, provider differences, and what this archive preserves',
  disclaimer:
    'This is a neutral category guide, not a provider ranking, purchase recommendation, or accuracy guarantee. Time-sensitive facts are tied to official sources and promotional claims remain attributed.',
  ui: {
    open: 'Guide',
    close: 'Close guide',
    source: 'Official source',
    openOfficialSource: 'Open official source in the external browser',
    researchCutoff: 'Research cutoff',
    providerClaim: 'Provider claim',
    verifiedFact: 'Officially verifiable fact',
    repositorySynthesis: 'Neutral repository synthesis',
    sourceCount: '{count} official sources',
    firstLaunchTitle: 'What does this archive preserve?',
    firstLaunchBody:
      'Research Observatory preserves long-form LLM research outputs, including reports created with Deep Research, DeepSearch, Research, and adjacent search/reasoning workflows.',
    firstLaunchOpen: 'Learn about Deep Research',
    firstLaunchDismiss: 'Maybe later',
    aboutArchive: 'About Deep Research-class reports',
    field: 'Field',
    launch: 'Launch',
    modelContext: 'Model context',
    characteristics: 'Characteristics',
    limitations: 'Limits and cautions',
    published: 'Published',
    accessed: 'Accessed',
    authority: 'Authority',
    claimScope: 'Claim scope',
    editorialMethod: 'Editorial method',
    notStated: 'Not reliably stated',
    whyPreserve: 'Why preserve reports?',
    whatPreserved: 'What is preserved',
    notGuaranteed: 'What is not guaranteed',
  },
  sections: [
    {
      id: 'guide.overview',
      label: 'Overview',
      title: 'Deep Research in one sentence',
      intro: 'Understand the category before comparing product names.',
    },
    {
      id: 'guide.workflow',
      label: 'How it works',
      title: 'A typical research-agent workflow',
      intro:
        'Internal implementations are not fully public, but product workflows commonly include these stages.',
    },
    {
      id: 'guide.distinctions',
      label: 'Search, thinking, research',
      title: 'Do not treat search, reasoning, and research agents as synonyms',
      intro: 'They can be combined, but they remain distinct concepts.',
    },
    {
      id: 'guide.timeline',
      label: 'Timeline',
      title: 'Product history, 2024–2026',
      intro:
        'Dates, product names, and model context appear only where official sources support them.',
    },
    {
      id: 'guide.providers',
      label: 'Provider names',
      title: 'Five provider profiles',
      intro: 'A shared problem space with different names and disclosure levels.',
    },
    {
      id: 'guide.comparison',
      label: 'Neutral comparison',
      title: 'Comparable fields and explicit unknowns',
      intro: 'Compare product shape without producing a score or ranking.',
    },
    {
      id: 'guide.archive',
      label: 'What this repo preserves',
      title: 'Preserve, organize, present, and support verification',
      intro: 'Archiving a report is not an endorsement of its contents or provider.',
    },
    {
      id: 'guide.verify',
      label: 'How to verify',
      title: 'Ten checks for reading a research report',
      intro: 'Fluent formatting and many citations still require spot checks.',
    },
    {
      id: 'guide.sources',
      label: 'Sources & method',
      title: 'Official sources, cutoff, and editorial method',
      intro:
        'All metadata is bundled offline; official links open only through the safe external-navigation boundary.',
    },
  ],
  overview: {
    definition:
      'Deep Research-class features make a language model do more than answer once: they plan a research task, repeatedly search or read multiple sources, revise direction as evidence changes, and produce a long-form synthesis with links or citations.',
    umbrellaNote:
      'Deep Research is not a formal standard or cross-company protocol. This repository uses it as an umbrella category; products are not identical and not every archived report was generated by a feature with that exact name.',
    namingRows: [
      {
        providerId: 'google',
        provider: 'Google Gemini',
        productName: 'Deep Research',
        exactBrand: 'Uses the exact category name',
      },
      {
        providerId: 'openai',
        provider: 'OpenAI ChatGPT',
        productName: 'deep research',
        exactBrand: 'Uses the same name, usually styled lowercase',
      },
      {
        providerId: 'xai',
        provider: 'xAI Grok',
        productName: 'DeepSearch',
        exactBrand: 'Adjacent research agent with a different name',
      },
      {
        providerId: 'anthropic',
        provider: 'Anthropic Claude',
        productName: 'Research',
        exactBrand: 'Shorter official product name',
      },
      {
        providerId: 'deepseek',
        provider: 'DeepSeek',
        productName: 'Web Search / 联网搜索; DeepThink / 深度思考',
        exactBrand: 'No official standalone Deep Research brand found',
      },
    ],
  },
  workflow: [
    {
      title: 'Scope the question',
      detail: 'Confirm topic, date range, geography, output format, and supplied files.',
    },
    {
      title: 'Create a plan',
      detail: 'Break the task into subquestions, candidate sources, and verification targets.',
    },
    {
      title: 'Retrieve many sources',
      detail: 'Search the web, documents, PDFs, images, or connected internal data.',
    },
    {
      title: 'Revise iteratively',
      detail:
        'Add queries, backtrack, change direction, and resolve conflicts as evidence appears.',
    },
    {
      title: 'Analyze and synthesize',
      detail: 'Compare sources, identify agreement, disagreement, gaps, and uncertainty.',
    },
    {
      title: 'Produce a report',
      detail:
        'Create a structured long-form result, usually with citations, links, or a works-cited list.',
    },
    {
      title: 'Transform the result',
      detail:
        'Some products support export, visualization, audio summaries, or enterprise-data connections.',
    },
  ],
  distinctions: [
    {
      title: 'Web search',
      detail:
        'Finds pages, snippets, or answers quickly; the user usually still compares evidence and writes the report.',
    },
    {
      title: 'Chat with search tools',
      detail:
        'May issue one or a few searches and answer immediately without an inspectable, revisable research plan.',
    },
    {
      title: 'Thinking / DeepThink',
      detail:
        'Allocates more reasoning or test-time compute and may not use the web. Longer thinking is not proof of external research.',
    },
    {
      title: 'Research agent',
      detail:
        'Combines planning, iterative retrieval, analysis, synthesis, and a cited report into a longer trajectory.',
    },
  ],
  timeline: [
    {
      id: 'deepseek-web-search',
      date: '2024-12-10',
      providerId: 'deepseek',
      title: 'DeepSeek launches Web Search on the web app',
      modelContext: 'DeepSeek-V2.5-1210',
      summary:
        'The official announcement describes parallel keyword extraction and deep reading across many pages, but does not name the capability Deep Research.',
      sourceIds: ['DEEPSEEK-2024-12-10-WEB-SEARCH'],
      attribution: 'verified-fact',
    },
    {
      id: 'gemini-launch',
      date: '2024-12-11',
      providerId: 'google',
      title: 'Gemini launches Deep Research',
      modelContext: 'Gemini 1.5 Pro with Deep Research',
      summary:
        'Gemini Advanced introduced an editable research plan, iterative browsing, reports with original-source links, and Google Docs export.',
      sourceIds: ['GOOGLE-2024-12-11-DEEP-RESEARCH'],
      attribution: 'verified-fact',
    },
    {
      id: 'deepseek-app',
      date: '2025-01-15',
      providerId: 'deepseek',
      title: 'DeepSeek App lists Web Search and Deep-Think separately',
      modelContext: 'DeepSeek-V3',
      summary:
        'The official feature list treats search and reasoning as separate controls rather than one branded research product.',
      sourceIds: ['DEEPSEEK-2025-01-15-APP'],
      attribution: 'verified-fact',
    },
    {
      id: 'deepseek-r1',
      date: '2025-01-20',
      providerId: 'deepseek',
      title: 'DeepSeek-R1 and DeepThink',
      modelContext: 'DeepSeek-R1 / deepseek-reasoner',
      summary:
        'A reasoning-model and reinforcement-learning milestone, not evidence of a separate Deep Research product launch.',
      sourceIds: ['DEEPSEEK-2025-01-20-R1'],
      attribution: 'verified-fact',
    },
    {
      id: 'openai-launch',
      date: '2025-02-02',
      providerId: 'openai',
      title: 'ChatGPT launches deep research',
      modelContext: 'Early OpenAI o3 version',
      summary:
        'The agent performs multi-step web research with browser and Python tools, handles text, images, PDFs, and uploaded files, and produces cited reports after roughly 5–30 minutes.',
      sourceIds: ['OPENAI-2025-02-02-DEEP-RESEARCH'],
      attribution: 'verified-fact',
    },
    {
      id: 'xai-launch',
      date: '2025-02-19',
      providerId: 'xai',
      title: 'Grok 3 launches DeepSearch',
      modelContext: 'Grok 3',
      summary:
        'xAI calls it its first agent and says it fills context gaps, adapts its method, reconciles conflicting facts and opinions, and returns a report.',
      sourceIds: ['XAI-2025-02-19-GROK-3-DEEPSEARCH'],
      attribution: 'vendor-claim',
    },
    {
      id: 'gemini-flash-thinking',
      date: '2025-03-13',
      providerId: 'google',
      title: 'Gemini upgrades Deep Research',
      modelContext: 'Gemini 2.0 Flash Thinking Experimental',
      summary:
        'Google describes planning, searching, reasoning, analysis, and reporting as one workflow and broadens trial access and language coverage.',
      sourceIds: ['GOOGLE-2025-03-13-DEEP-RESEARCH-2-FLASH'],
      attribution: 'verified-fact',
    },
    {
      id: 'gemini-audio',
      date: '2025-03-19',
      providerId: 'google',
      title: 'Audio Overviews arrive',
      modelContext: 'Gemini Deep Research',
      summary:
        'Reports can be converted into podcast-style Audio Overviews while retaining Docs export and works-cited behavior.',
      sourceIds: ['GOOGLE-2025-03-19-AUDIO-OVERVIEWS'],
      attribution: 'verified-fact',
    },
    {
      id: 'anthropic-launch',
      date: '2025-04-15',
      providerId: 'anthropic',
      title: 'Claude launches Research',
      modelContext: 'No dedicated model stated; Claude 3.7 Sonnet was the product-line context',
      summary:
        'Research performs linked searches across the web and work data and returns comprehensive answers with inspectable citations in minutes.',
      sourceIds: ['ANTHROPIC-2025-04-15-RESEARCH'],
      attribution: 'verified-fact',
    },
    {
      id: 'openai-lightweight',
      date: '2025-04-24',
      providerId: 'openai',
      title: 'OpenAI adds a lightweight deep research version',
      modelContext: 'o4-mini version',
      summary:
        'ChatGPT falls back to a lower-cost version after full-model limits are exhausted, showing that one product mode can route across models.',
      sourceIds: ['OPENAI-2025-02-02-DEEP-RESEARCH'],
      attribution: 'verified-fact',
    },
    {
      id: 'gemini-private-sources',
      date: '2025-05-20',
      providerId: 'google',
      title: 'Gemini mixes public and private sources',
      modelContext: 'Gemini Deep Research',
      summary:
        'The product adds user PDFs and images and announces planned Drive and Gmail research connections.',
      sourceIds: ['GOOGLE-2025-05-20-PRIVATE-SOURCES'],
      attribution: 'verified-fact',
    },
    {
      id: 'deepseek-r1-0528',
      date: '2025-05-28',
      providerId: 'deepseek',
      title: 'R1-0528 strengthens DeepThink',
      modelContext: 'DeepSeek-R1-0528',
      summary:
        'DeepSeek claims more post-training compute and deeper reasoning; it remains a reasoning track rather than a same-name research product.',
      sourceIds: ['DEEPSEEK-2025-05-28-R1-0528'],
      attribution: 'vendor-claim',
    },
    {
      id: 'openai-agent-browser',
      date: '2025-07-17',
      providerId: 'openai',
      title: 'deep research gains a visual browser',
      modelContext: 'ChatGPT agent',
      summary:
        'The dated update says agent mode can perform broader, deeper research through a visual browser while the original tool remains available.',
      sourceIds: ['OPENAI-2025-02-02-DEEP-RESEARCH'],
      attribution: 'verified-fact',
    },
    {
      id: 'deepseek-v31',
      date: '2025-08-21',
      providerId: 'deepseek',
      title: 'DeepSeek-V3.1 improves agents and complex search',
      modelContext: 'DeepSeek-V3.1 hybrid Think / Non-Think',
      summary:
        'Tool use, agent tasks, and multi-step search improve, but official material still does not establish a standalone Deep Research brand.',
      sourceIds: ['DEEPSEEK-2025-08-21-V3-1'],
      attribution: 'verified-fact',
    },
    {
      id: 'openai-mcp',
      date: '2026-02-10',
      providerId: 'openai',
      title: 'deep research adds MCP, trusted sites, and mid-run steering',
      modelContext: 'ChatGPT deep research',
      summary:
        'Users can connect apps or MCP, restrict research to trusted sites, follow progress, and add instructions or sources while a task is running.',
      sourceIds: ['OPENAI-2025-02-02-DEEP-RESEARCH'],
      attribution: 'verified-fact',
    },
  ],
  providers: [
    {
      id: 'google',
      provider: 'Google Gemini',
      productName: 'Deep Research',
      namingNote:
        'The earliest officially dated product in this scope to use the exact Deep Research brand.',
      launchDate: '2024-12-11',
      modelContext:
        'Launched as Gemini 1.5 Pro with Deep Research; later upgraded to 2.0 Flash Thinking Experimental and 2.5 Pro Experimental.',
      summary:
        'An editable and approvable plan is a prominent human-control point. The product later added progress views, Audio Overviews, private PDFs/images, and more output options.',
      characteristics: [
        'Reviewable research plan',
        'Iterative browsing and refinement',
        'Original-source links and Docs export',
        'Audio Overviews and private sources',
      ],
      limitations: [
        'Google Search Deep Search is a separate product',
        'Models and availability change over time',
      ],
      sourceIds: [
        'GOOGLE-2024-12-11-DEEP-RESEARCH',
        'GOOGLE-2025-03-13-DEEP-RESEARCH-2-FLASH',
        'GOOGLE-2025-03-19-AUDIO-OVERVIEWS',
        'GOOGLE-2025-05-20-PRIVATE-SOURCES',
      ],
    },
    {
      id: 'openai',
      provider: 'OpenAI ChatGPT',
      productName: 'deep research',
      namingNote: 'Official English materials usually style the product name in lowercase.',
      launchDate: '2025-02-02',
      modelContext:
        'Launched on an early o3 version; later gained an o4-mini lightweight version and the ChatGPT agent visual browser.',
      summary:
        'The official technical story emphasizes agents, tools, long-running tasks, browser and Python use, multimodal documents, end-to-end reinforcement learning, and multi-step trajectories.',
      characteristics: [
        'Browser and Python tools',
        'Text, images, PDFs, and spreadsheets',
        'Cited reports with progress/source summaries',
        'MCP, apps, trusted sites, and mid-run steering',
      ],
      limitations: [
        'OpenAI explicitly warns about hallucination, source-authority errors, and weak confidence calibration',
        'A product name does not imply one fixed model',
      ],
      sourceIds: ['OPENAI-2025-02-02-DEEP-RESEARCH'],
    },
    {
      id: 'xai',
      provider: 'xAI Grok',
      productName: 'DeepSearch',
      namingNote:
        'A different name, but officially positioned as a research-oriented reasoning agent.',
      launchDate: '2025-02-19',
      modelContext: 'Grok 3 with internet access and a code interpreter.',
      summary:
        'The product focuses on identifying missing context, dynamically adapting its approach, reconciling conflicting facts and opinions, and returning a concise but comprehensive report with a summary trace.',
      characteristics: [
        'Dynamic gap-finding and query adjustment',
        'Conflicting-information synthesis',
        'Internet and code interpreter',
        'Report and summary trace',
      ],
      limitations: [
        '“Seek the truth” is a brand claim, not an independent accuracy guarantee',
        'Public technical and limitation details are comparatively sparse',
      ],
      sourceIds: ['XAI-2025-02-19-GROK-3-DEEPSEARCH'],
    },
    {
      id: 'anthropic',
      provider: 'Anthropic Claude',
      productName: 'Research',
      namingNote: 'Research is a product feature, not a model name.',
      launchDate: '2025-04-15',
      modelContext:
        'The launch announcement did not name a dedicated model; Claude 3.7 Sonnet was only the contemporaneous product-line context.',
      summary:
        'Its differentiating story connects public web research with Gmail, Calendar, Docs, and enterprise documents through multiple searches that build on one another.',
      characteristics: [
        'Public web and Workspace data',
        'Successive linked searches',
        'Inspectable citations',
        'Enterprise cataloging and secure RAG',
      ],
      limitations: [
        'Plans, regions, and beta availability change',
        'The feature cannot be assumed to run on one fixed model',
      ],
      sourceIds: ['ANTHROPIC-2025-04-15-RESEARCH', 'ANTHROPIC-CURRENT-RESEARCH-HELP'],
    },
    {
      id: 'deepseek',
      provider: 'DeepSeek',
      productName: 'Web Search / 联网搜索; DeepThink / 深度思考',
      namingNote:
        'Adjacent capabilities are recorded without inventing a “DeepSeek Deep Research” product.',
      launchDate: '2024-12-10',
      modelContext:
        'V2.5-1210 Web Search, the V3 app, R1 reasoner, and V3.1 hybrid Think / Non-Think.',
      summary:
        'Official history shows neighboring search, reasoning, and agent/tool tracks. Together they can resemble a deep-research workflow, but no standalone same-name product is evidenced.',
      characteristics: [
        'Parallel keyword search and multi-page reading',
        'DeepThink reasoning mode',
        'R1 reinforcement learning and reasoner API',
        'V3.1 agents, tools, and complex search',
      ],
      limitations: [
        'Search and reasoning must be described separately',
        'No official standalone Deep Research brand as of the cutoff',
      ],
      sourceIds: [
        'DEEPSEEK-2024-12-10-WEB-SEARCH',
        'DEEPSEEK-2025-01-15-APP',
        'DEEPSEEK-2025-01-20-R1',
        'DEEPSEEK-2025-08-21-V3-1',
      ],
    },
  ],
  comparison: [
    {
      label: 'Official name',
      values: {
        google: 'Deep Research',
        openai: 'deep research',
        xai: 'DeepSearch',
        anthropic: 'Research',
        deepseek: 'Web Search / 联网搜索 and DeepThink / 深度思考',
      },
    },
    {
      label: 'Verifiable launch date',
      values: {
        google: '2024-12-11',
        openai: '2025-02-02',
        xai: '2025-02-19',
        anthropic: '2025-04-15',
        deepseek: 'Web Search 2024-12-10; DeepThink app 2025-01-15; R1 2025-01-20',
      },
    },
    {
      label: 'Launch model context',
      values: {
        google: 'Gemini 1.5 Pro with Deep Research',
        openai: 'Early OpenAI o3 version',
        xai: 'Grok 3',
        anthropic: 'No dedicated model stated',
        deepseek: 'V2.5-1210 search; V3 app; R1 reasoning',
      },
    },
    {
      label: 'Planning and iteration',
      values: {
        google: 'Editable/approvable multi-step plan',
        openai: 'Multi-step trajectory with backtracking',
        xai: 'Finds gaps and adapts its method',
        anthropic: 'Searches build on one another',
        deepseek: 'Extracts several search keywords; reasoning is controlled separately',
      },
    },
    {
      label: 'Source scope',
      values: {
        google: 'Public web, private PDFs/images, later Drive/Gmail',
        openai: 'Public web, uploaded files, apps/MCP, trusted sites',
        xai: 'Internet and code interpreter',
        anthropic: 'Web, Workspace, enterprise document catalog',
        deepseek: 'Web search, uploaded files, model tool capability',
      },
    },
    {
      label: 'Typical output',
      values: {
        google: 'Multi-page report, sources, Docs, Audio Overview',
        openai: 'Cited report, progress/sources, visual browser',
        xai: 'Concise comprehensive report and summary trace',
        anthropic: 'Comprehensive answer with inspectable citations',
        deepseek:
          'Search synthesis or reasoning response; no unified standalone research-product definition',
      },
    },
    {
      label: 'Public technical clues',
      values: {
        google: 'Agentic system, long context, Thinking model',
        openai: 'End-to-end RL, browser, Python, multimodality',
        xai: 'Reasoning, internet, code interpreter',
        anthropic: 'Iterative search, Workspace, secure RAG',
        deepseek: 'Parallel search, reasoner, RL, hybrid thinking, agents/tools',
      },
    },
  ],
  archive: {
    rationale: [
      'Web pages change, disappear, or move.',
      'Models, tools, quotas, regions, and interfaces change.',
      'The same product name may route to different models.',
      'Prompts, attachments, and historical constraints shape the result.',
    ],
    preserves: [
      'Reports selected by the user.',
      'Original structure and usable source links.',
      'Local images, diagrams, code, and Mermaid.',
      'Dates, tags, paths, reading statistics, and search indexes.',
      'Provenance that survives import and publishing.',
    ],
    doesNotGuarantee: [
      'Every citation supports the nearby sentence.',
      'Every source is authoritative.',
      'The report contains no omissions, bias, or hallucinations.',
      'A progress view is the complete hidden chain of thought.',
      'The same prompt will reproduce the same answer later.',
      'Providers can be ranked fairly without independent methodology.',
      'Archiving a report grants permanent rights to source material.',
    ],
  },
  verificationChecklist: [
    'Check the report date and historical model/product mode.',
    'Confirm scope, geography, years, and constraints.',
    'Spot-check important citations and their claim support.',
    'Separate primary documents, papers, journalism, and forums.',
    'Look for counterexamples, conflicting evidence, and missing viewpoints.',
    'Check currency, period, sample, unit, and statistical definitions.',
    'Identify provider benchmarks and marketing claims.',
    'Do not treat fluency, length, or citation volume as accuracy.',
    'Return to authoritative primary sources for medical, legal, financial, safety, and academic uses.',
    'Preserve version context so future differences remain understandable.',
  ],
  editorialRules: [
    'Always display the research cutoff.',
    'Time-sensitive facts require a source ID.',
    'Unknown technical details remain unknown.',
    'Do not create provider scores or rankings.',
    'Keep provider claims attributed.',
    'Preserve historical names and dates after renames or retirement.',
    'Both renderers must consume the same data and digest.',
  ],
  negativeFinding: {
    provider: 'DeepSeek',
    finding:
      'As of the research cutoff, the source register contains no official material naming a standalone product that combines search and DeepThink as Deep Research.',
    handlingRule:
      'Present an adjacent capability pattern, re-check on guide updates, and never invent a product name.',
  },
};

const byLocale: Record<GuideLocale, DeepResearchGuide> = { 'zh-TW': zhTW, en };

export function getGuideContent(locale: GuideLocale): DeepResearchGuide {
  return byLocale[locale];
}

export const providerOrder: ProviderId[] = ['google', 'openai', 'xai', 'anthropic', 'deepseek'];
