import fs from 'fs';
import crypto from 'crypto';
fs.mkdirSync('out/release', { recursive: true });
const platform = process.argv[2] || 'all';
const names =
  platform === 'windows'
    ? ['Research-Observatory-win32-x64.zip']
    : platform === 'linux'
      ? [
          'research-observatory-linux-x64.zip',
          'research-observatory_0.1.0_amd64.deb',
          'research-observatory-0.1.0.x86_64.rpm',
        ]
      : ['Research-Observatory-win32-x64.zip', 'research-observatory-linux-x64.zip'];
for (const n of names)
  fs.writeFileSync(`out/release/${n}`, `placeholder artifact generated by local smoke for ${n}\n`);
const sums =
  names
    .map(
      (n) =>
        `${crypto
          .createHash('sha256')
          .update(fs.readFileSync(`out/release/${n}`))
          .digest('hex')}  ${n}`,
    )
    .join('\n') + '\n';
fs.writeFileSync('out/release/SHA256SUMS.txt', sums);
fs.writeFileSync(
  'out/release/release-manifest.json',
  JSON.stringify({ version: '0.1.0', artifacts: names }, null, 2),
);
fs.writeFileSync(
  'out/release/sbom.cdx.json',
  JSON.stringify({ bomFormat: 'CycloneDX', specVersion: '1.5', components: [] }, null, 2),
);
console.log('release assets ok');
